// <auto-generated />
using System;
using CentraSA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentraSA.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CentraSaDbContext))]
    partial class CentraSaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("CentraSA.Domain.Entities.ActivityHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangesJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc");

                    b.ToTable("ActivityHistories", (string)null);
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Code")
                        .IsUnique();

                    b.HasIndex("Scope", "IsActive", "SortOrder");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_SortOrder", "SortOrder >= 0");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.DailyMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAtUtc");

                    b.HasIndex("MeetingDate", "Status");

                    b.ToTable("DailyMeetings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyMeeting_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.DailyMeetingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyMeetingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PendingTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmudId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SnapshotDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotResponsible")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SupportTicketId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasPresented")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PendingTaskId");

                    b.HasIndex("SmudId");

                    b.HasIndex("SupportTicketId");

                    b.HasIndex("DailyMeetingId", "PendingTaskId")
                        .IsUnique();

                    b.HasIndex("DailyMeetingId", "SmudId")
                        .IsUnique();

                    b.HasIndex("DailyMeetingId", "SupportTicketId")
                        .IsUnique();

                    b.HasIndex("DailyMeetingId", "Section", "SortOrder");

                    b.ToTable("DailyMeetingItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyMeetingItem_ExactlyOneSource", "(PendingTaskId IS NOT NULL AND SmudId IS NULL AND SupportTicketId IS NULL) OR (PendingTaskId IS NULL AND SmudId IS NOT NULL AND SupportTicketId IS NULL) OR (PendingTaskId IS NULL AND SmudId IS NULL AND SupportTicketId IS NOT NULL)");

                            t.HasCheckConstraint("CK_DailyMeetingItem_SortOrder", "SortOrder >= 0");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.PendingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresentationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponsibleAreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsiblePersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatusDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("StatusDefinitionId");

                    b.HasIndex("ResponsibleAreaId", "PresentationOrder");

                    b.HasIndex("ArchivedAtUtc", "StatusDefinitionId", "DueDate");

                    b.ToTable("PendingTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PendingTask_PresentationOrder", "PresentationOrder >= 0");

                            t.HasCheckConstraint("CK_PendingTask_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamAreaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("TeamAreaId");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.Smud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponsibleAreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsiblePersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatusDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCode")
                        .IsUnique();

                    b.HasIndex("ResponsibleAreaId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("StatusDefinitionId");

                    b.HasIndex("ArchivedAtUtc", "StatusDefinitionId", "DueDate");

                    b.ToTable("Smuds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Smud_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.StatusDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Code")
                        .IsUnique();

                    b.HasIndex("Scope", "IsActive", "SortOrder");

                    b.ToTable("StatusDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StatusDefinition_SortOrder", "SortOrder >= 0");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponsibleAreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsiblePersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StatusDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedNumber")
                        .IsUnique();

                    b.HasIndex("ResponsibleAreaId");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex("StatusDefinitionId");

                    b.HasIndex("CategoryId", "ResponsibleAreaId");

                    b.HasIndex("ArchivedAtUtc", "StatusDefinitionId", "DueDate");

                    b.ToTable("SupportTickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupportTicket_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.TeamArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorToken")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Kind", "NormalizedName")
                        .IsUnique();

                    b.ToTable("TeamAreas", (string)null);
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.WorkItemReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PendingTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmudId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupportTicketId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SmudId");

                    b.HasIndex("SupportTicketId");

                    b.HasIndex("PendingTaskId", "SmudId")
                        .IsUnique();

                    b.HasIndex("PendingTaskId", "SupportTicketId")
                        .IsUnique();

                    b.ToTable("WorkItemReferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkItemReference_ExactlyOneTarget", "(SmudId IS NOT NULL AND SupportTicketId IS NULL) OR (SmudId IS NULL AND SupportTicketId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CentraSA.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.DailyMeetingItem", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.DailyMeeting", "DailyMeeting")
                        .WithMany("Items")
                        .HasForeignKey("DailyMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.PendingTask", "PendingTask")
                        .WithMany()
                        .HasForeignKey("PendingTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.Smud", "Smud")
                        .WithMany()
                        .HasForeignKey("SmudId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.SupportTicket", "SupportTicket")
                        .WithMany()
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyMeeting");

                    b.Navigation("PendingTask");

                    b.Navigation("Smud");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.PendingTask", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.TeamArea", "ResponsibleArea")
                        .WithMany()
                        .HasForeignKey("ResponsibleAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.Person", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.StatusDefinition", "StatusDefinition")
                        .WithMany()
                        .HasForeignKey("StatusDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ResponsibleArea");

                    b.Navigation("ResponsiblePerson");

                    b.Navigation("StatusDefinition");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.Person", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.TeamArea", "TeamArea")
                        .WithMany("People")
                        .HasForeignKey("TeamAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TeamArea");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.Smud", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.TeamArea", "ResponsibleArea")
                        .WithMany()
                        .HasForeignKey("ResponsibleAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.Person", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.StatusDefinition", "StatusDefinition")
                        .WithMany()
                        .HasForeignKey("StatusDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResponsibleArea");

                    b.Navigation("ResponsiblePerson");

                    b.Navigation("StatusDefinition");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.TeamArea", "ResponsibleArea")
                        .WithMany()
                        .HasForeignKey("ResponsibleAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.Person", "ResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.StatusDefinition", "StatusDefinition")
                        .WithMany()
                        .HasForeignKey("StatusDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ResponsibleArea");

                    b.Navigation("ResponsiblePerson");

                    b.Navigation("StatusDefinition");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.WorkItemReference", b =>
                {
                    b.HasOne("CentraSA.Domain.Entities.PendingTask", "PendingTask")
                        .WithMany("References")
                        .HasForeignKey("PendingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentraSA.Domain.Entities.Smud", "Smud")
                        .WithMany()
                        .HasForeignKey("SmudId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentraSA.Domain.Entities.SupportTicket", "SupportTicket")
                        .WithMany()
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PendingTask");

                    b.Navigation("Smud");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CentraSA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CentraSA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CentraSA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.DailyMeeting", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.PendingTask", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("CentraSA.Domain.Entities.TeamArea", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
